runtime: python27
api_version: 1
threadsafe: true
service: egrc-angular-hmg
handlers:
- url: /
  static_files: dist/GRC/index.html
  upload: dist/GRC/index.html
- url: /
  static_dir: dist/GRC
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  #- ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10